import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

SEV_COLORS = {
    "critical": colors.HexColor("#c0392b"),
    "high":     colors.HexColor("#d35400"),
    "medium":   colors.HexColor("#2471a3"),
    "low":      colors.HexColor("#1e8449"),
    "info":     colors.HexColor("#7f8c8d"),
}

def generate_pdf(scan):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
    )
    title_s = ParagraphStyle("T", fontSize=20, fontName="Helvetica-Bold", spaceAfter=4)
    sub_s   = ParagraphStyle("S", fontSize=10, textColor=colors.grey, spaceAfter=2)
    h2_s    = ParagraphStyle("H2", fontSize=13, fontName="Helvetica-Bold", spaceBefore=12, spaceAfter=6)
    body_s  = ParagraphStyle("B", fontSize=9, leading=14)
    label_s = ParagraphStyle("L", fontSize=8, fontName="Helvetica-Bold", textColor=colors.grey)

    story = [
        Spacer(1, 0.5*cm),
        Paragraph("Vulnerability Scan Report", title_s),
        Paragraph("Target: " + scan["url"], sub_s),
        Paragraph("Scanned: " + scan["scanned_at"] + " UTC", sub_s),
        HRFlowable(width="100%", thickness=1, color=colors.lightgrey, spaceAfter=10),
    ]

    s = scan["summary"]
    summary_data = [
        ["Critical", "High", "Medium", "Low", "Info"],
        [
            str(s.get("critical", 0)),
            str(s.get("high", 0)),
            str(s.get("medium", 0)),
            str(s.get("low", 0)),
            str(s.get("info", 0)),
        ],
    ]
    t = Table(summary_data, colWidths=[3.2*cm]*5)
    t.setStyle(TableStyle([
        ("ALIGN",           (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME",        (0, 0), (-1,  0), "Helvetica-Bold"),
        ("FONTSIZE",        (0, 1), (-1,  1), 18),
        ("TEXTCOLOR",       (0, 0), (0,  -1), SEV_COLORS["critical"]),
        ("TEXTCOLOR",       (1, 0), (1,  -1), SEV_COLORS["high"]),
        ("TEXTCOLOR",       (2, 0), (2,  -1), SEV_COLORS["medium"]),
        ("TEXTCOLOR",       (3, 0), (3,  -1), SEV_COLORS["low"]),
        ("BOX",             (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("INNERGRID",       (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("TOPPADDING",      (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING",   (0, 0), (-1, -1), 8),
    ]))

    story.append(Paragraph("Summary", h2_s))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("Findings", h2_s))

    order = ["critical", "high", "medium", "low", "info"]
    findings = sorted(
        scan.get("findings", []),
        key=lambda f: order.index(f.get("severity", "info"))
    )

    for i, f in enumerate(findings, 1):
        sev = f.get("severity", "info").lower()
        color = SEV_COLORS.get(sev, colors.grey)
        story.append(Paragraph(
            "#" + str(i) + " [" + sev.upper() + "] " + f.get("title", ""),
            ParagraphStyle(
                "FH", fontSize=10, fontName="Helvetica-Bold",
                textColor=color, spaceBefore=8
            )
        ))
        if f.get("owasp"):
            story.append(Paragraph(f.get("owasp"), label_s))
        if f.get("description"):
            story.append(Paragraph(f["description"], body_s))
        if f.get("evidence"):
            story.append(Paragraph(
                "Evidence: " + f["evidence"],
                ParagraphStyle(
                    "E", fontSize=8, fontName="Courier",
                    backColor=colors.HexColor("#f7f7f7"), leading=12
                )
            ))
        if f.get("recommendation"):
            story.append(Paragraph("Fix: " + f["recommendation"], body_s))
        story.append(Spacer(1, 0.2*cm))

    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey, spaceAfter=6))
    story.append(Paragraph(
        "Generated by Vuln Scanner | " + datetime.utcnow().strftime("%Y-%m-%d %H:%M") + " UTC",
        ParagraphStyle("F", fontSize=7, textColor=colors.grey)
    ))

    doc.build(story)
    return buf.getvalue()
